# dein本体。基本は repo に github のリポジトリを設定するだけでよい
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'tomasr/molokai'

# [[plugins]]
# repo = 'scrooloose/syntastic'


[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'ervandew/supertab'

[[plugins]]
repo = 'tyru/caw.vim'

[[plugins]]
repo = 'Shougo/unite.vim.git'

[[plugins]]
repo = 'Shougo/vimfiler'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'skanehira/preview-markdown.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'arcticicestudio/nord-vim'

[[plugins]]
repo = 'ryanoasis/vim-devicons'
